# Generated by Django 5.1.4 on 2025-12-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_mk', models.CharField(help_text='Macedonian name', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('универзална', 'Универзална')], max_length=20)),
                ('color', models.CharField(choices=[('бела', 'Бела'), ('црна', 'Црна'), ('црвена', 'Црвена'), ('сина', 'Сина'), ('зелена', 'Зелена'), ('жолта', 'Жолта'), ('розова', 'Розова'), ('сива', 'Сива'), ('кафена', 'Кафена'), ('портокалова', 'Портокалова'), ('виолетова', 'Виолетова'), ('златна', 'Златна'), ('сребрена', 'Сребрена'), ('слонова-коска', 'Слонова Коска'), ('бордо', 'Бордо'), ('темно-сина', 'Темно Сина'), ('смарагдна', 'Смарагдна')], max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('image_path', models.CharField(help_text='Path to product image', max_length=500)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured products')),
                ('is_new', models.BooleanField(default=False, help_text='Show in new collection')),
                ('is_popular', models.BooleanField(default=False, help_text='Show in popular models')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'availability'], name='products_pr_categor_6b96c3_idx'), models.Index(fields=['is_featured', 'is_new', 'is_popular'], name='products_pr_is_feat_bc0ab0_idx')],
            },
        ),
    ]
