# Generated by Django 5.1.4 on 2025-12-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_mk', models.CharField(max_length=100, verbose_name='Македонско име')),
                ('description', models.TextField(blank=True)),
                ('description_mk', models.TextField(blank=True, verbose_name='Македонски опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.IntegerField(help_text='Estimated delivery time in days')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Креирана'), ('packed', 'Спакувана'), ('shipped', 'Испратена'), ('in_transit', 'Во транспорт'), ('out_for_delivery', 'На испорака'), ('delivered', 'Доставена'), ('failed', 'Неуспешна')], default='created', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100, verbose_name='Куриерска служба')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Забелешки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('delivery_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryoption')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.delivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
