# Generated by Django 5.1.4 on 2025-12-22 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, verbose_name='Презиме')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефонски број')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Емаил')),
                ('reservation_date', models.DateField(verbose_name='Датум')),
                ('reservation_time', models.TimeField(verbose_name='Време')),
                ('status', models.CharField(choices=[('pending', 'На чекање'), ('confirmed', 'Потврдена'), ('completed', 'Завршена'), ('cancelled', 'Откажана'), ('no_show', 'Не се појави')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Забелешки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
    ]
