# Generated by Django 5.1.4 on 2025-12-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('category_based', 'По категорија'), ('product_based', 'По производ'), ('bundle', 'Пакет понуда')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount % for bundle offer', max_digits=5)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules show first')),
                ('recommended_categories', models.ManyToManyField(blank=True, related_name='recommended_in_rules', to='products.category')),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='recommended_in_rules', to='products.product')),
                ('trigger_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_triggers', to='products.category')),
                ('trigger_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_triggers', to='products.product')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
